openstreetmap/mod_tile

- src/gen_tile.cpp
Fixes #141 .
As discussed in https://github.com/gravitystorm/openstreetmap-carto/issues/2391 and https://github.com/gravitystorm/openstreetmap-carto/issues/2397 , the Noto CJK fonts that the openstreetmap-carto style uses are currently not used on the rendering servers. They have the extension ".ttc" and are supported by Mapnik.
I have not tested this pull request, but I assume it will solve the problem.
> Also load TTC font files

- src/gen_tile.cpp
Looks like mapnik 3.0.12 is using mapnik::util::variant which is incompatible with char*. Quick and simple fix is to wrap it in std::string on assignment.
Havent tested this with older versions of mapnik but it should be good?
> Issue #132 Fixed compilation for Mapnik 3.0.12

- includes/daemon.h
- includes/render_submit_queue.h
- src/daemon.c
- src/render_expired.c
- src/render_list.c
- src/render_old.c
- src/render_submit_queue.c
> Move variables to prevent duplicates

- docs/renderd.8
- src/daemon.c
- src/mod_tile.c
- src/protocol_helper.c
Author: Bas Couwenberg
Origin: [spelling-errors.patch](https://salsa.debian.org/xamanu/libapache2-mod-tile/-/blob/c80f8cc216c0aba38ae3f58e605fc585cfe64441/debian/patches/spelling-errors.patch)
* recieve   -> receive
* accross   -> across
* determins -> determines
* reqyest   -> request
> Fix some spelling errors.

- debian/tileserver_site.conf
- mod_tile.conf
I fixed a few typos, and brought over some config examples
from mod_tile.conf into the Debian example debian/tileserver_site.conf
which is deployed as part of the Debian install into /etc/apache2.
> Conf typos fixed, merging confs.

- docs/render_list.1
**Added .SH OPTIONS to docs/render_list.1**
The description for render_list man page options was missing.
I would like to add them with this PR
> Added .SH OPTIONS to docs/render_list.1

- src/daemon.c
- src/mod_tile.c
This is a rebased version of #208 given the original requestor hasn't responded to the request to rebase and we are now running into this on tile.openstreetmap.org:
select() has a well-known limit and the maximum file descriptor
that can be used (FD_SETSIZE). On Linux it is in most cases 1024.
Our renderd uses a lot of planet tiff files, so it had already
more than 1600 FDs for tiff files open. That means any new FD gets a
number bigger than that and using such FDs in select() leads to crashes
(because select() uses a fixed size bitmap).
The same can happen in mod_tile if the surounding web server is very
busy, altough it is less likely to happen there.
Changes in src/mod_tile.c:
- include poll.h
- poll timeout is an int containing miliseconds
- use "s > 0" instead of "s == 1" as success …
> Replace select() by poll().

- src/mod_tile.c
Be a bit more verbose in case of errors, to make finding the root cause easier
> include details in error log message

- src/render_submit_queue.c
As noted in https://github.com/openstreetmap/mod_tile/pull/229#pullrequestreview-705434980 my previous fix to reconnect automatically didn't retry the failed command so this adds looping on the command when it fails and we have to reconnect.
> Retry a failed command after reconnecting

- README.rst
Explicitly state that Debian helper scripts require packages and configuration section does not apply when building from source.
Fixes #241 misunderstanding.
> Explicitly mention Debian packages for config

- src/mod_tile.c
Add a Prometheus `/metrics` endpoint based on the modtile_collector[0]
script.
* Minor metric naming cleanup.
* Drops duplicate TileBufferReads metrics that duplicate the per-zoom values.
Related to: https://github.com/openstreetmap/operations/issues/492
[0]: https://github.com/openstreetmap/prometheus-exporters/blob/main/collectors/modtile/modtile_collector
Signed-off-by: Ben Kochie <superq@gmail.com>
> Add a Prometheus metrics endpoint

- .gitignore
* `Makefile.am` ignored by `Makefile*`
* `etc/renderd/*` ignored by `renderd`
> Fix `.gitignore` ignoring too much

- Makefile.am
This fixes the build issue on Fedora identified in #248 by converting `-pthread` to `-Wc,-pthread` when invoking apxs.
> Convert -pthread to -Wc,-pthread when invoking apxs

- .github/workflows/build-and-test-centos-7.yml
- docs/building_on_centos_7.md
* Requires several packages from `EPEL` repository
* Requires building `Mapnik`
* Caches `Mapnik` build directory
* Takes about 20-30 minutes without cache
* Takes about 5-10 minutes with cache
* Runs on `push` to `centos7` branch & on `pull_request`
* Includes very basic build documentation
> Added build & test on CentOS 7

- src/daemon.c
- src/parameterize_style.cpp
* Changed logging level for empty/absent `parameterize_style` to `DEBUG`
* Addresses this message currently being shown once per thread during initialization:
```
** INFO: 04:05:50.327: Loading parameterization function for
```
* Fixed two minor grammar issues: `to` => `too`
> Minor logging changes

- includes/protocol.h
- src/render_list.c
- src/render_submit_queue.c
Signed-off-by: Stephan Austermühle <au@hcsd.de>
Fixes #137 
This PR allows tools like `render_list` to connect to `renderd` over network instead of local Unix sockets allowing for easy separation of `mod_tile` and `renderd`. Also, it enables connecting to dynamically scaling `renderd` instances (e.g., when deployed on a Kubernetes cluster). Simply pass `-s ‹hostname›:‹tcpPort›` instead of a Unix socket path to use.
Feedback on this PR is welcome.
> Allow connections over TCP besides Unix sockets for tools

- configure.ac
- src/daemon.c
- src/render_expired.c
- src/render_list.c
- src/render_old.c
- src/speedtest.cpp
Relates to #263
As well as updating the alignment of option `descriptions` and adding `--version`/`-V` to `render*` commands for displaying version information.
Also added the version number to `renderd` output, I.E.:
```
** INFO: 17:45:23.458: Rendering daemon started (version 0.6.1)
** INFO: 17:45:23.458: Initialising request_queue
** INFO: 17:45:23.458: Parsing section renderd
** INFO: 17:45:23.458: Parsing render section 0
** INFO: 17:45:23.458: Parsing section mapnik
** INFO: 17:45:23.458: config renderd: unix socketname=/run/renderd/renderd.sock
** INFO: 17:45:23.458: config renderd: num_threads=4
** INFO: 17:45:23.458: config renderd: num_slaves=0
** INFO: 17:45:23.458: config renderd: tile_dir=/var/cache/renderd/tiles
** INFO: 17:45:23.458: config renderd: …
```
> Updated `Usage` to reflect recent change allowing TCP for tools

- etc/renderd/renderd.conf
- etc/renderd/renderd.conf.examples
- includes/daemon.h
- includes/render_config.h
- src/daemon.c
Defaults to previous value, so existing deployment configurations will be unaffected.
> Added PID file path configurability

- includes/daemon.h
- src/cache_expire.c
- src/daemon.c
- src/mod_tile.c
- src/parameterize_style.cpp
- src/store_rados.c
* Resolved `cppcheck` error `memleak` in `src/store_rados.c`
* `store` was not being `free`d (see [here](https://github.com/hummeltech/mod_tile/blob/a14924a999d0c465a023c02301964c41700744f1/src/store_rados.c#L354-L356))
* Resolved `cppcheck` error `memleak` in `src/parameterize_style.cpp`
* `data` was not being `free`d (see [here](https://github.com/hummeltech/mod_tile/blob/a14924a999d0c465a023c02301964c41700744f1/src/parameterize_style.cpp#L42-L44))
* Resolved all compiler warnings `discarded-qualifiers` in `src/daemon.c`
* Warnings can be seen [here](https://github.com/openstreetmap/mod_tile/runs/6538303841?check_suite_focus=true#step:9:327)
* Resolved compiler warning `format=` in `src/mod_tile.c`
* Warning can be seen [here](https://github.com/openstreetmap/mod_tile/runs/6538303841?che …
> Resolve various compiler warnings and errors

- .github/workflows/flawfinder-analysis.yml
This allows the relevant lines to be highlighted for more easily visualizing the issues.
**Before:**
**After:**
> Don't use dot-prefixed (I.E. current directory) paths for Flawfinder scan

- docs/man/render_speedtest.1
- includes/catch.hpp
- src/gen_tile_test.cpp
- src/render_expired.c
- src/render_list.c
- src/render_old.c
- src/speedtest.cpp
**Also:** 
* Added test for `renderd --version`
* Adjusted exit codes for `render_*`
* Added zoom-level range specification support for `render_speedtest`
* Modified man page for `render_speedtest`
* `render_speedtest` was renamed from `speedtest` in e8001c859f9aff20a387a57b7b3c9bee7beb921b
* Upgraded `catch.hpp` to Catch2 v2.13.9
> Added basic `gen_tile_test` tests for `render_*`

- .github/workflows/build-and-test.yml
Ubuntu repositories no longer support 21.04, switching to 22.04 LTS instead.
```shell
> docker run --interactive --rm --tty ubuntu:21.04 apt-get update
Ign:1 http://security.ubuntu.com/ubuntu hirsute-security InRelease
Err:2 http://security.ubuntu.com/ubuntu hirsute-security Release
404  Not Found [IP: 185.125.190.36 80]
Ign:3 http://archive.ubuntu.com/ubuntu hirsute InRelease
Ign:4 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu hirsute-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu hirsute Release
404  Not Found [IP: 185.125.190.39 80]
Err:7 http://archive.ubuntu.com/ubuntu hirsute-updates Release
404  Not Found [IP: 185.125.190.39 80]
Err:8 http://archive.ubuntu.com/ubuntu hirsute-backports Release
404  Not Found [IP: …
```
> Removed Ubuntu 21.04 (replace it with Ubuntu 22.04)

- docs/build/building_on_ubuntu_20_04.md
The workflow name is now "build-and-test.yml", so change the 20.04 build doc (which still works for 22.04) to point to that.
Also spelling of "Continuous".
> Updated Ubuntu 20.04 doc to fix link to build and test .yml

- src/daemon_compat.c
* It should be `HAVE_SYS_CDEFS_H`
* From `configure.ac`: (`AC_CHECK_HEADERS([sys/cdefs.h])`)
* See [here](https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Generic-Headers.html#index-AC_005fCHECK_005fHEADERS-1) for documentation
Working towards simplifying things in https://github.com/openstreetmap/mod_tile/pull/284.
> Fixed typo `HAVE_SYS_CDEFS_C`

- src/mod_tile.c
* `s6_addr32` is defined neither in `macOS` nor `FreeBSD`
Working towards simplifying things in https://github.com/openstreetmap/mod_tile/pull/284.
> Fixed macOS build support

- src/mod_tile.c
* To indicate system headers are expected
Working towards simplifying things in https://github.com/openstreetmap/mod_tile/pull/284.
> Adjust header include enclosures in `src/mod_tile.c`

- Makefile.am
- configure.ac
- src/daemon.c
* Rather than relying on the OS (I.E. `#ifdef __FreeBSD__`)
Working towards simplifying things in https://github.com/openstreetmap/mod_tile/pull/284.
> Allow either `iniparser.h` or `iniparser/iniparser.h`

- README.rst
- docs/build/building_on_debian_12.md
The Ubuntu 20.04 docs don't work exactly for Debian 12. So here's some docs.
----
_(BTW I am not an expert in Debian packaing etc, so please excuse any beginner mistakes)_
see also https://github.com/openstreetmap/mod_tile/issues/295
> Add docs on how to compile on Debian 12

- src/daemon.c
- tests/CMakeLists.txt
- tests/httpd.conf.in
- tests/renderd.conf.in
Currently `renderd*` sections must be read in first in order to populate the `num_threads` & `tile_dir` values for each `map` section.
https://github.com/openstreetmap/mod_tile/blob/d8a0f29cfe0b8ae15db4e3d3ccf3981366e3bcbf/src/daemon.c#L838-L841
This change will allow `renderd*` sections to be anywhere within the `renderd` config file by first reading the prerequisite `renderd*` section(s) and then reading any `map` section(s).
> Allow `renderd*` sections to follow `map` sections in `renderd.conf`

- .github/workflows/build-and-test.yml
* `Debian 12` released on `2023-06-10`
* `Debian 10` security updates were discontinued on `2022-06-30`
> Replace `Debian 10` with `Debian 12` in GitHub Actions

- .github/actions/cmake/build/action.yml
- .github/actions/dependencies/build-and-install/mapnik/latest/action.yml
- .github/actions/dependencies/install/action.yml
- .github/workflows/build-and-test.yml
* `Fedora 38` released on `2023-04-18`
* `Fedora 36` EOLed on `2023-05-16`
See [here](https://github.com/hummeltech/mod_tile/actions/runs/5190297895) for an example GitHub Actions workflow run.
> Replace `Fedora 36` with `Fedora 38` in GitHub Actions

- .github/actions/dependencies/install/action.yml
- .github/workflows/build-and-test.yml
Available since April 24th, 2023:
https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/
This version of `macOS` seems to generally run a few minutes faster, about 6-9 minutes total rather than 11-14 minutes.
> Make macOS 13 the default macOS version in GitHub Actions

- .github/actions/freebsd/action.yml
So it no longer needs to be built in order to test `mod_tile`, this will greatly speed up `FreeBSD` jobs in GitHub CI.
(From @ 30 minutes to @ 10 minutes)
Mapnik added here:
https://github.com/freebsd/freebsd-ports/commit/84c697c41d13d0bc8d1fe1cf9d6f81410c77630f
> Mapnik is now in FreeBSD's package repositories

- tests/CMakeLists.txt
Since `render_speedtest` is run, we should make sure the remaining `render_*` targets run without failing.
> Add basic CMake tests for remaining `render_*` targets

- CMakeLists.txt
It will default to the previous destination, the result of `apxs -q libexecdir`.
> Added ability to customize HTTP server module installation directory

- .github/actions/cmake/install/action.yml
- .github/actions/cmake/test/action.yml
- .github/workflows/build-and-test.yml
- CMakeLists.txt
- etc/apache2/tile.load.in
- etc/renderd/renderd.conf.in
- includes/config.h.in
- includes/protocol.h
- includes/render_config.h
- src/convert_meta.c
- src/daemon.c
- src/mod_tile.c
- src/render_expired.c
- src/render_list.c
- src/render_old.c
- src/render_submit_queue.c
- src/speedtest.cpp
- tests/CMakeLists.txt
- tests/httpd.conf.in
- tests/renderd.conf.in
Since most of the variables contained within config files and related to directory destinations are available at build time, they can be used to generate and install some of the config files and directories.
* `/etc/renderd.conf`
* Basic `renderd` configuration file with `renderd` & `mapnik` sections
* `/etc/apache2/mods-available/tile.load` (path varies based on OS/Distribution)
* Apache HTTP server `LoadModule` directive configuration file
* `/var/run/renderd`
* `/var/cache/renderd/tiles`
> Generate config files and directories with CMake

- etc/renderd/renderd.conf.examples
- includes/daemon.h
- src/daemon.c
- src/gen_tile.cpp
- src/mod_tile.c
- tests/CMakeLists.txt
- tests/renderd.conf.in
- utils/example-map/index.html
Replaces #191 (thanks @timautin!) as it has been inactive for @ 2.3 years:
> Added the possibility to provide ImageIO's output format in the TYPE string of the renderd.conf file.
> For instance:
> TYPE=png image/png
> TYPE=png image/png png256
> TYPE=png image/png png24
> TYPE=png image/png png
> 
> This should be backward compatible with existing renderd.conf files.
Also added additional tests for various image output formats:
* **jpeg**
* `TYPE=jpg image/jpeg jpeg`
* **png256**
* `TYPE=png image/png png256`
* **png32**
* `TYPE=png image/png png32`
* **webp**
* `TYPE=webp image/webp webp`
Closes #64
Closes #301
> Configurable ImageIO output format

- .github/actions/cmake/build/action.yml
- .github/actions/dependencies/install/yum/action.yml
- .github/actions/freebsd/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/coverage.yml
- tests/CMakeLists.txt
- tests/renderd.conf.in
* Fix `Unknown argument "--skip-broken" for command "dnf5"` (`fedora:rawhide`)
* Increase timeout for `render_list` & `render_old` tests (`centos:7`)
* Add support for testing with `libwebp.so.4` (`centos:7`)
* Sync FreeBSD build command with others (and build Release by default)
* Fix non-default (I.E. `.jpg`/`.webp`/etc.) tile tests
* `mapnik.xml` file was no longer being copied to `@PROJECT_BINARY_DIR@` since [this commit](https://github.com/hummeltech/mod_tile/commit/6e20fba5e9817cd16c41943b223f47c461288f5a#diff-c0b18b5ea11fcb76f961f9651a40e5d596a11c1ab7076f8f9c43402e19fc7858L6-L10)
> Fixed various CI failures

- src/gen_tile.cpp
If the local font cache is not populated then mapnik falls back to trying to use the global cache which is buggy and has nasty lock contention issues (https://github.com/mapnik/mapnik/issues/4406) so we want to call `load_fonts` on the map to populate it.
Because copying map objects discards the cache we want to avoid doing that unless we have to, and when we do have to because the map is parameterized we defer loading the fonts until after the copy is made.
> Pre-load fonts so map's local font cache is populated

- src/render_submit_queue.c
This attempts to minimise the time that the lock is help when taking a job from the queue and scales the queue size with the number of threads to try and ensure it stays full enough to keep all threads busy.
> Improve lock contention in render_list etc

- includes/render_config.h
When these limits were set in 2008 (a16d3b7) it would take a few minutes to clear through the dirty tile queue, giving it the ability to even out load over a few minute timescale, and let the work in the queue be done when the server is no longer busy. These days, a server can clear through 1000 metatiles in seconds, meaning the queue fills up nearly instantly and starts dropping tiles.
Increasing these limits by 8x attempts to restore some of the old utility of the queue.
By my estimates, in 2008 a server might have been doing 5 metatiles/second, while now it's 100 metatiles/second.
If we were starting over, I wouldn't consider the gains of having the queue worth the additional code complexity.
> Increase queue limits to reflect modern machines

- .github/actions/freebsd/action.yml
The `ceph14` package has been marked as `broken` and is therefore no longer available:
https://github.com/freebsd/freebsd-ports/commit/02f9ff5be452447269234bad74d082c102a8e8d1
This is causing errors such as this:
https://github.com/openstreetmap/mod_tile/actions/runs/6322159276/job/17167290842#step:3:1249
> Fixed FreeBSD CI build failure

- tests/CMakeLists.txt
* Deprecated with [CMake 3.27](https://cmake.org/cmake/help/latest/module/FindDart.html), which is currently only present in `Fedora Rawhide`
* [Before](https://github.com/hummeltech/mod_tile/actions/runs/5618193893/job/15223412223#step:6:63)
* [After](https://github.com/hummeltech/mod_tile/actions/runs/5624575307/job/15241662030#step:6:63)
> Resolve deprecation of CMake module `FindDart`

- tests/CMakeLists.txt
- tests/httpd.conf.in
- tests/renderd.conf.in
* Allow customizing `httpd` & `renderd` CTest testing TCP ports
> CTest testing customizations & improvements

- .github/workflows/build-and-test.yml
FreeBSD's `mapnik` package is currently not being built due to some minor errors, once it is fixed, this job will begin to pass again.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274166
> Allow FreeBSD job to fail

- .github/workflows/build-and-test.yml
Currently failing:
```
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```
> Fix CentOS 7 CI job not working with `actions/checkout@v4`

- .github/workflows/build-and-test.yml
- docs/build/building_on_freebsd.md
Mapnik v3.1.0 requires a patch in order to support Boost v1.8.3.
A fix has been applied, but has not yet made it into the quarterly repository:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274166
> FreeBSD quarterly repo is now missing `mapnik`

- docs/man/render_expired.1
- src/render_expired.c
When running `render_expired` as part of regular updates lots of progress messages just clog up the logs.
> Add a --no-progress switch to render_expired

- .github/actions/cmake/test/action.yml
Apparently `${{ runner.temp }}` has a different value under certain circumstances
> Fix build artifacts not uploading

- .github/actions/dependencies/install/action.yml
- .github/workflows/build-and-test.yml
- tests/CMakeLists.txt
- tests/httpd.conf.in
- tests/renderd.conf.in
The `freebsd-vagrant-action` action now supports running on `Linux` runners, which almost halves the duration of `FreeBSD` building and testing.
> Improve FreeBSD CI Workflow

- docs/build/building_on_macos.md
On `macOS`, the directory `/usr` is read-only (except for `/usr/local`, at least).
Resolves #349
> Fix macOS `cmake --install` command failing due to `Read-only file system`

- .github/actions/cmake/test/action.yml
- .github/workflows/coverage.yml
- docker/debian/Dockerfile
- docker/ubuntu/Dockerfile
- tests/CMakeLists.txt
- tests/httpd.conf.in
- tests/renderd.conf.in
_Also_:
* Added background `renderd` process testing
* Added `renderd` section without `stats_file` testing
* Added `render_*` via TCP tests
* Added `render_* --verbose`  tests
* Added `render_expired --delete-from` tests
* Added `render_expired --no-progress` tests
* Added `render_expired --touch-from` tests
* Added `PARAMETERIZE_STYPE=language` map configuration testing
* Added `HTCPHOST`/`HOST` map configuration testing
> Add tests for MemcacheD storage backend

- docker/docker-compose.yml
- docker/ubuntu/entrypoint.sh
By taking advantage of `YAML anchors`: https://docs.docker.com/compose/compose-file/10-fragments/
_Also_:
- Added `full` service to `docker/docker-compose.yml` (including real osm data and openstreetmap carto)
- Under `ubuntu-devel-full`
- I.E. (`cd docker && docker compose up ubuntu-devel-full`)
- In order to more fully test
> Simplifed `docker/docker-compose.yml` file

- etc/apache2/renderd-example-map.conf
- etc/renderd/renderd.conf.examples
- src/store_memcached.c
- tests/CMakeLists.txt
- tests/httpd.conf.in
- tests/renderd.conf.in
So that MemcacheD hosts and ports other than `localhost` and `11211` can be used.
_Also_:
- Added `ctest --parallel` execution support
- Added tests for custom `MemcacheD` {host}:{port}
- Added tests for `AddTileConfig`/`AddTileMimeConfig`
> Allow `host:port` specification for memcached storage backend

- etc/apache2/renderd-example-map.conf
- tests/CMakeLists.txt
- tests/renderd.conf.in
_Also_:
- Removed `AddTileMimeConfig` from example `HTTPD` config
- No longer needed after merging #346
- Deprecation notice incoming with #370
- Added additional `AddTileConfig`/`AddTileMimeConfig` tests
- Testing failing download with invalid map name in `httpd.conf`
- Testing parsing invalid `httpd.conf`, e.g.:
- `LoadTileConfigFile` without arguments
- `LoadTileConfigFile` without non-existent file
- Replaced `grep` with `${GREP_EXECUTABLE}` in tests
> Updated `AddTileConfig` documentation in example `HTTPD` config

- src/mod_tile.c
- tests/CMakeLists.txt
_Also_:
- Changed `AddTileConfig` parsing directive
- From `AP_INIT_RAW_ARGS` to `AP_INIT_TAKE_ARGV`
- Makes code a bit cleaner, e.g.:
- Checking for first two "arguments"
- Iterating "arguments"
- Applied Artistic Style Formatting 
- After merging #346
- Added deprecation notice when using `AddTileMimeConfig`
- Enabled commented `AddTileConfig`/`AddTileMimeConfig` tests
> Added `tile_dir` support to `AddTileConfig`

- .github/actions/dependencies/install/action.yml
- .github/workflows/build-and-test.yml
- tests/CMakeLists.txt
* To facilitate running `memcached` tests for all jobs
* `CentOS`/`Debian`/`Fedora` jobs don't seem to like running `memcached` on `localhost`
* `FreeBSD` jobs don't seem to like running `memcached` on `0.0.0.0`
> Allow custom host specification with CTest

- docs/man/renderd.conf.5
- src/renderd.c
- tests/CMakeLists.txt
- tests/renderd.conf.in
When configuring `num_threads=-1` in `renderd.conf` for a `renderd` section, the value will be set to the number of cores on the running system.
Resolves #379
> Add option to detect available cores when num_threads=-1

- .github/workflows/build-and-test.yml
- includes/config.h.in
- includes/g_logger.h
- includes/mod_tile.h
- includes/parameterize_style.hpp
- includes/request_queue.h
- includes/store.h
- src/cache_expire.c
- src/gen_tile.cpp
- src/gen_tile_test.cpp
- src/mod_tile.c
- src/render_submit_queue.c
- src/renderd.c
- src/request_queue.c
- src/store_file.c
* `includes/config.h.in`
* Wrap contents in `#ifndef CONFIG_H`
* `includes/mod_tile.h`
* Include `protocol.h`
* For `XMLCONFIG_MAX`
* Include `apr_tables.h`
* For `apr_array_header_t`/`apr_time_t`/`apr_uint64_t`
* Include `netinet/in.h`
* For `in6_addr`/`in_addr_t`
* `src/cache_expire.c`
* Include `netinet/in.h`
* For `htonl`/`htons`
* `src/gen_tile.cpp`
* Use `snprintf` instead of `sprintf`
* To resolve `warning: 'sprintf' is deprecated` in [`macOS` builds](https://github.com/openstreetmap/mod_tile/actions/runs/7590268635/job/20677236621#step:5:579)
* `src/gen_tile_test.cpp`
* Use `snprintf` instead of `sprintf`
* To resolve `warning: 'sprintf' is deprecated` in [`macOS` builds](https://github.com/openstreetmap/mod_tile/actions/runs/7590268635/job/20677236621#step:5:579)
* …
> Address compiler warnings

- .github/workflows/build-and-test.yml
- CMakeLists.txt
- includes/g_logger.h
- src/g_logger.c
- src/gen_tile.cpp
- src/mod_tile.c
- src/render_expired.c
- src/render_list.c
- src/render_old.c
- src/render_speedtest.cpp
- src/renderd.c
- src/store.c
- tests/gen_tile_test.cpp
And setting it to `0`, no longer requiring defining it everywhere except in foreground executables as needed.
_Also_:
* Require `GLib` >= `v2.50`
* Needed for [g_log_writer_standard_streams](https://docs.gtk.org/glib/func.log_writer_standard_streams.html)
* Set FreeBSD job `BUILD_PARALLEL_LEVEL` & `TEST_PARALLEL_LEVEL` environment variables via `run`
* Rather than hard-coding them
> Move `foreground` definition into `src/g_logger.c`

- .github/actions/cmake/test/action.yml
- src/mod_tile.c
- tests/CMakeLists.txt
This only seems to happen after a delay pool is created (i.e. when `ModTileEnableTileThrottling` is enabled) and is then being manipulated.
> Handle `mod_tile` not having a valid storage context (causing a segmentation fault)

- includes/cache_expire.h
- includes/gen_tile.h
- includes/metatile.h
- includes/mod_tile.h
- includes/protocol.h
- includes/protocol_helper.h
- includes/render_config.h
- includes/render_submit_queue.h
- includes/request_queue.h
- includes/store.h
- includes/store_file.h
- includes/store_file_utils.h
- includes/store_memcached.h
- includes/store_null.h
- includes/store_rados.h
- includes/store_ro_composite.h
- includes/store_ro_http_proxy.h
- src/cache_expire.c
- src/gen_tile.cpp
- src/metatile.cpp
_Also_:
* Use `mapnik::freetype_engine::register_fonts` in `gen_tile.cpp` rather than recursing manually
* Available since `Mapnik` v2 which is no longer supported
> Minor Clean Up of includes and gen_tile.cpp

- docs/man/render_expired.1
- docs/man/render_list.1
- src/render_expired.c
- src/render_list.c
- src/render_old.c
- src/render_speedtest.cpp
- src/render_submit_queue.c
_Also updated all render\_* apps to_:
* Use `MAX_ZOOM` rather than hard-coded values for `--max-zoom`
* Print `metatile` rather than `meta tile`
* Add missing `--help` output to `render_expired` & `render_list`
* Remove redundant `--help` output from `render_list`
> Update man pages for render_expired/render_list

- .github/actions/autotools/install/action.yml
- .github/workflows/build-and-test.yml
- docs/build/building_on_macos.md
Available since January 30th, 2024:
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
> Add macOS 14 to build and test CI workflow

- .github/workflows/build-and-test.yml
- docs/build/building_on_freebsd.md
- src/mod_tile.c
- tests/CMakeLists.txt
- tests/httpd.conf.in
* Previously it was not actually sending the header
* Now runs in serial, regardless of parallel specification
* Now runs only once, rather than for each map layer
_Also_:
* Removed no-longer used `storage_mutex`
* Was only used for Apache HTTP Server < v2.4
> Fix/improve X-Forwarded-For/throttling testing

- .github/workflows/build-and-test.yml
- .github/workflows/docker-image-build.yml
- .github/workflows/install-package-and-test.yml
- docker/README.md
- docker/docker-compose.yml
So that workflows will still show  as passing.
* Build & Test
* debian:unstable
* fedora:rawhide
* ubuntu:devel
* Docker Image Build
* debian-unstable/debian-unstable-autotools
* fedora-rawhide
* opensuse-tumbleweed
* ubuntu-devel/ubuntu-devel-autotools
> Added `continue-on-error` for experimental distros

- CMakeLists.txt
- docs/man/render_list.1
- includes/renderd_config.h
- src/CMakeLists.txt
- src/render_list.c
- src/renderd_config.c
- tests/CMakeLists.txt
- tests/render_expired_test.cpp
- tests/render_list_test.cpp
- tests/render_old_test.cpp
- tests/render_speedtest_test.cpp
* Fix `render_list` build needs `libm`
* Add tests
* Update man page
* Create function to set double
* Clean up / optimize a bit
* Remove `--dont-render` option
> Follow up to #190 for `render_list`

- src/renderd_config.c
- tests/renderd_config_test.cpp
In order to remove any confusion if the user has duplicate `renderd` sections in their `renderd.conf` file.
Currently with a configuration like this one:
```ini
[renderd]
pid_file=/run/renderd/renderd.pid
socketname=/run/renderd/renderd.sock
stats_file=/run/renderd/renderd.stats
tile_dir=/var/cache/renderd/tiles
[renderd0]
pid_file=/run/renderd/renderd0.pid
socketname=/run/renderd/renderd0.sock
stats_file=/run/renderd/renderd0.stats
tile_dir=/var/cache/renderd/tiles
```
only the second `renderd` section (`renderd0`) will actually be used.
After this patch is merged, an error message will be shown and the application will exit.
> Prevent duplicate `renderd` sections in `renderd.conf`

- .github/actions/autotools/build/action.yml
- .github/actions/coverage/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/docker-image-build.yml
- docker/README.md
- docker/docker-compose.yml
- docker/opensuse/Dockerfile
- docs/build/building_on_fedora.md
_And_:
* Remove Fedora 38
* Fix `openSUSE Leap 15` Docker build's default GCC no longer compiles `Mapnik` latest
* C++17 is now required, so a newer GCC will be installed
* Fix for coverage capturing with LCOV 2.1
* Seems to currently only exist on macOS
> Add Fedora 40 to build pipeline

- includes/render_config.h
Resolves https://github.com/openstreetmap/mod_tile/issues/396
> Increase `XMLCONFIGS_MAX` default from `10` to `100`

- .github/actions/coverage/action.yml
- docs/build/building_on_ubuntu.md
- src/parameterize_style.cpp
* `.github/actions/coverage/action.yml`
* Ignore `unused` errors when excluding coverage directories
* `docs/build/building_on_ubuntu.md`
* Fix typo
* `src/parameterize_style.cpp`
* Use `auto` rather than `std::optional<std::string>`/`boost::optional<std::string>`
> Minor fixes

- docs/build/building_on_centos_stream.md
After removal of CentOS Stream 8 / CentOS 7 documentation removal.
> Update CentOS Stream build documentation

- .github/workflows/build-and-test.yml
- CMakeLists.txt
- README.rst
- tests/gen_tile_test.cpp
`libcurl` & `libcairo` are also optional and their usage can now be optionally disabled (along with `libmemcached` & `librados`.)
> Clarify optional libraries and allow optionally disabling them

- CMakeLists.txt
- src/CMakeLists.txt
With new `CMake CACHE` entry `MALLOC_LIB`, supporting the following values:
* `libc` (default): Use the system's implementation
* `jemalloc`: Use [jemalloc](http://jemalloc.net)
* `mimalloc`: Use [mimalloc](https://github.com/microsoft/mimalloc)
* `tcmalloc`: Use [tcmalloc](https://github.com/google/tcmalloc)
> Allow linking alternate memory management implementations

- src/renderd.c
- src/renderd_config.c
The memory allocated by `strndup` needs to be freed.
The code has also been changed to not lose the allocation pointer and according to the semantics of `strtok_r` explained here:
https://man.freebsd.org/cgi/man.cgi?query=strtok_r
Also improved messaging.
> Fix memory leak during configuration parsing

- .github/actions/dependencies/install/action.yml
- docker/fedora/Dockerfile
- docs/build/building_on_fedora.md
It contains libraries now referenced by `pkg-config` and `mod_tile` uses only `pkg-config` for `Mapnik >= v4.0.0`.
> Fedora rawhide requires mapnik-static (now that it provides Mapnik v4.0.0)

- src/renderd.c
Otherwise `renderd` processes configured to use TCP/IP server sockets may need to wait until the address and/or port are released before restarting under certain circumstances (especially an ungraceful termination).
> Enable `SO_REUSE{ADDR,PORT}` for `renderd` TCP/IP server sockets

- .github/workflows/build-and-test.yml
- src/mod_tile.c
Rather than named shared memory segments (see [here](https://apr.apache.org/docs/apr/trunk/group__apr__shm.html#gac370c4943c22505ce2b0d57c51805480)).
Fixes tests on `macOS` unable to run in parallel, which was likely an indicator of a greater issue with `macOS` builds
> Use anonymous shared memory segments for `mod_tile.so`

- src/mod_tile.c
Should resolve #441 and resolve #464.
> Also account for tileVeryOld state in add_expiry and tile_handler_status

- .github/workflows/build-and-test.yml
- Fix failing `Mapnik Latest` tests:
- `Debian 12`'s [boost](https://github.com/mapnik/mapnik/blob/master/CHANGELOG.md#mapnik-405) is too old for `Mapnik` >= `v4.0.5`
- Fix failing `macOS` coverage
- `format` & `category` errors have been popping up recently
> CI pipeline test fixes

- src/mod_tile.c
- tests/CMakeLists.txt
Also moved `cors = NULL` fix from #479 into `_add_tile_config` instead as that fix only applied to configs added via `AddTileConfig` in `httpd.conf` files, not all methods.
> Add `Origin` header test for CORS not being set
