openstreetmap/mod_tile

src/gen_tile.cpp
Load opentype fonts in font directories.
=> scan & register opentype fonts

openstreetmap-tiles-update-expire
As I'm not working at Personalwerk anymore, I moved the service to my own Server
=> replicate-seqences-tool has long been moved

src/render_submit_queue.c
Rerolled https://github.com/openstreetmap/mod_tile/pull/128 by @tomhughes on the latest codebase.
This is up for testing.
=> Make render_list reconnect if the renderd connection is lost

.github/workflows/github-actions.yml
* Split into multiple dependent jobs
* Added test for `mod_tile` Apache HTTP Server module
* Install, configure & start `apache` & `renderd`
=> Update GitHub Actions configuration

.github/actions/apt/install/action.yml, .github/actions/apt/update/action.yml, .github/actions/build-archive/create/action.yml, .github/actions/build-archive/extract/action.yml, .github/workflows/github-actions.yml
Also add compression to build archives to save time and drive space.
=> Reduce redundant CI configuration by using local actions

src/daemon.c, src/gen_tile_test.cpp, src/mod_tile.c
Credits to @leforestier from where I sourced the code changes. See https://github.com/leforestier/mod_tile/commit/de9b83e0a89b3621bef4a1b8ced8691c0aed8131
=> Fix compile errors on FreeBSD

docs/man/render_expired.1, docs/man/render_list.1, docs/man/render_speedtest.1, docs/man/renderd.1
=> Update man pages to reflect recent changes

src/gen_tile_test.cpp, src/store_ro_http_proxy.c
* From `CodeQL`:
* `src/store_ro_http_proxy.c`
* Wrong type of arguments to formatting function
* From `Flawfinder`:
* `src/gen_tile_test.cpp`
* Ignore alerts about `system` & `popen` as this is expected and used only for testing
* Remove unused `char * buf_tmp` in two test sections
* Use `sizeof` rather than `strlen`
* Use `snprintf` rather than `sprintf`
=> Fixing a few minor source code issues

etc/apache2/renderd-example-map.conf, includes/mod_tile.h, src/mod_tile.c, tests/CMakeLists.txt, tests/httpd.conf.in
=> Make `/status` and `/dirty` URLs controlable with apache conf

AUTHORS, CMakeLists.txt, Makefile.am, docs/man/convert_meta.1, docs/man/openstreetmap-tiles-update-expire.1, docs/man/render_expired.1, docs/man/render_list.1, docs/man/render_old.1, docs/man/render_speedtest.1, docs/man/renderd.1, docs/man/renderd.conf.5
=> Add man page for renderd.conf

src/mod_tile.c
AddTileConfig is a shorthand way of adding tile configs without a renderd.conf; if you use mod_tile with tirex, then you will typically not have a renderd.conf and hence rely on AddTileConfig.
AddTileConfig lacks the richness of renderd.conf configuration; you cannot, for example, configure differing max_zooms or file extensions or mime types.
To partly fix this problem, AddTileMimeConfig was introduced which takes one extra argument - misleadingly, not the MIME type, but the file extension, as a third parameter.
This approach is not scalable and difficult to use because of the positional parameters.
This pull request introduces optional key-value pairs for the AddTileConfig directive. You can now write
AddTileConfig /tile tile mimetype=image/jpeg extension=jpg maxzoom=22
to configure …
=> allow key=value parameters for AddTileConfig

.github/actions/coverage/action.yml, .github/actions/dependencies/build-and-install/mapnik/latest/action.yml, .github/actions/dependencies/install/action.yml, .github/workflows/coverage.yml
_Also_:
* Don't build unneeded `latest` Mapnik `benchmarks`/`demos`/`utilities`
=> Report coverage for `latest` Mapnik as well

tests/httpd.conf.in
=> Prepend `host` to `Listen` directive in `httpd.conf` for `CTest`

.dockerignore, .github/workflows/docker-image-build.yml, docker/centos/stream/Dockerfile.autotools, docker/debian/Dockerfile.autotools, docker/docker-compose.yml, docker/ubuntu/Dockerfile.autotools
To make local Autotools build testing easier.
=> Add Autotools build Dockerfiles

docs/man/render_list.1, src/gen_tile_test.cpp, src/render_list.c
_Also_:
* Added checks for `min` & `max` `x`, `y` & `z` tile coordinate options in order to:
* Ensure they are integers
* Ensure they are positive
Resolves #387
=> Clarify `render_list` documentation

Makefile.am, includes/renderd.h, includes/renderd_config.h, src/CMakeLists.txt, src/gen_tile.cpp, src/parameterize_style.cpp, src/render_submit_queue.c, src/renderd.c, src/renderd_config.c, tests/CMakeLists.txt, tests/gen_tile_test.cpp, tests/httpd.conf.in, tests/renderd.conf.in
So that it can be easily re-used by other targets.
=> Move `renderd.conf` processing code into new file

includes/renderd_config.h, src/gen_tile.cpp, src/renderd.c, src/renderd_config.c
* Remove some usages of `sscanf`
* Rename `active_slave` to `active_renderd_section_num`
=> Minor adjustments to renderd_config.c

includes/store_file_utils.h, src/store_file_utils.c, tests/CMakeLists.txt, tests/httpd.conf.in
* Add tests for `ModTileCacheExtendedHostName` and expired tileOld/TileVeryOld
* Add tests for `ModTileEnableTileThrottling`/`ModTileEnableTileThrottlingXForward`
=> Additional tests

src/mod_tile.c, tests/CMakeLists.txt
https://github.com/openstreetmap/mod_tile/actions/runs/8014727426/attempts/4
=> Fix segmentation fault in modtile.c:delay_allowed

.github/actions/cmake/package/action.yml, CMakeLists.txt, src/render_expired.c, src/render_list.c
* Add project description and URL for CPack packaging
=> CPack Updates

src/renderd_config.c, tests/renderd_config_test.cpp
The maximum allowed length of a socket file name is 108:
https://www4.cs.fau.de/Services/Doc/C/libc.html#SEC189
Exceeding this length will likely lead to difficult to troubleshoot behavior.
=> Prevent socketnames in `renderd.conf` exceeding maximum allowed length

utils/munin/mod_tile_latency
=> Fix typo in utils/munin/mod_tile_latency

CMakeLists.txt
https://github.com/mapnik/mapnik/commit/a85bc9513563eff1e90407099d24b23dd7b02654
=> Mapnik v4.0.0 will require C++17

CMakeLists.txt, configure.ac, docs/man/convert_meta.1, docs/man/openstreetmap-tiles-update-expire.1, docs/man/render_expired.1, docs/man/render_list.1, docs/man/render_old.1, docs/man/render_speedtest.1, docs/man/renderd.1, docs/man/renderd.conf.5
In preparation for future release
=> Bumped version to 0.8.0

.github/workflows/install-package-and-test.yml, docker/debian/Dockerfile, docker/debian/Dockerfile.autotools, docker/docker-compose.yml
Fix `Dockerfile`s & `docker-compose.yml` to support this.
=> Debian Unstable and Ubuntu Devel now default to Mapnik v4.0.0

.github/workflows/docker-image-build.yml, docker/archlinux/Dockerfile, docker/centos/stream/Dockerfile, docker/centos/stream/Dockerfile.autotools, docker/centos/stream/Dockerfile.mapnik-latest, docker/debian/Dockerfile, docker/debian/Dockerfile.autotools, docker/docker-compose.yml, docker/fedora/Dockerfile, docker/opensuse/Dockerfile, docker/ubuntu/Dockerfile, docker/ubuntu/Dockerfile.autotools
* Add `Dockerfile` linting with `hadolint`
* Fix minor `Dockerfile` issues found by `hadolint`
=> Dockerfile cleaning

src/mod_tile.c
=> Fix typo in `mod_tile.c`

.github/workflows/build-and-test.yml, .github/workflows/docker-image-build.yml, docker/README.md, docker/archlinux/Dockerfile, docker/centos/stream/Dockerfile, docker/centos/stream/Dockerfile.autotools, docker/centos/stream/Dockerfile.mapnik-latest, docker/debian/Dockerfile, docker/debian/Dockerfile.autotools, docker/docker-compose.yml, docker/fedora/Dockerfile, docker/opensuse/Dockerfile, docker/ubuntu/Dockerfile, docker/ubuntu/Dockerfile.autotools, docs/build/building_on_fedora.md
=> Add `Fedora 42` to CI
